CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null')
  EMPTY_FIELD_AS_NULL = true;
 

 
CREATE OR REPLACE TABLE 
    MYDB.BRONZE.WORK_PRODUCT_COPY
(
    PRODUCT_ID VARCHAR(255) NOT NULL COLLATE 'en-ci'
,PRODUCT_NAME VARCHAR(255) NOT NULL COLLATE 'en-ci'
,CATEGORY VARCHAR(255) COLLATE 'en-ci'
,SELLING_PRICE VARCHAR(50) COLLATE 'en-ci'
    ,MODEL_NUMBER VARCHAR(50) COLLATE 'en-ci'
,ABOUT_PRODUCT VARCHAR(5000) COLLATE 'en-ci'
,PRODUCT_SPECIFICATION VARCHAR(5000) COLLATE 'en-ci'
,TECHNICAL_DETAILS VARCHAR(50000) COLLATE 'en-ci'
,SHIPPING_WEIGHT VARCHAR(30) COLLATE 'en-ci'
,PRODUCT_DIMENSIONS VARCHAR(100) COLLATE 'en-ci'
    ,INSERT_DTS TIMESTAMP_NTZ(6) NOT NULL
    ,UPDATE_DTS TIMESTAMP_NTZ(6) NOT NULL
    ,SOURCE_FILE_NAME VARCHAR(255) NOT NULL
    ,SOURCE_FILE_ROW_NUMBER VARCHAR(255) NOT NULL);

 
